server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monomer_db?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init.sql
  swagger:
    ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
    packages-to-scan: org.example.controller
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.example.entity

logging:
  level:
    root: info
    org.example: debug
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"