server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/monomer_db?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init.sql
  swagger:
    ui:
      path: /swagger-ui.html
    api-docs:
      path: /v3/api-docs
    packages-to-scan: org.example.controller

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.example.entity

logging:
  level:
    org.springframework: INFO
    com.baomidou: INFO